### ISSUE TITLE
`RuntimeError: unreachable` caused by string literal or comment containing `</`

### ISSUE THREAD

**Issue by yw662** [CodingCarter/minifier#5]
It is tested with : 
```ts
const minifier = import('https://deno.land/x/minifier/mod.ts')
minifier.minify('js', Deno.readTextFileSync(${file_path}))
```
Firstly I tried this:
```js
const a = 1
```
And it gives, as expected, `"const a = 1"`

However for this one:
```js
//</
const a = 1
```

It crashes with `RuntimeError: unreachable`:
```
Uncaught RuntimeError: unreachable
    at <anonymous> (<anonymous>:1:336424)
    at <anonymous> (<anonymous>:1:341096)
    at <anonymous> (<anonymous>:1:339419)
    at <anonymous> (<anonymous>:1:339781)
    at <anonymous> (<anonymous>:1:336272)
    at <anonymous> (<anonymous>:1:268321)
    at minify (<anonymous>:1:253183)
    at minify (https://deno.land/x/minifier@v1.1.1/wasm.js:98:14)
    at Module.minify (https://deno.land/x/minifier@v1.1.1/mod.ts:27:10)
    at <anonymous>:2:10
```

And (not) surprisingly these also fail:
```js
const a = '</'
```
and,
```js
const a = '</div>'
```
with the same `RuntimeError: unreachable`,

but these are good:
```js
const a = '<div></div>'
```
or this:
```js
const a = '<'
```

I am on Apple M1 device and `deno 1.8.0`.

**Comment by yw662** [comment]
Just found a workaround for that:
```js
minifier.minifyHTML(`<script>${code}</script>`, {minifyJS: true}).slice(8, -9)
```

<del>Will do a PR if you are glad with that</del>

Well this doesn't seem to minify the code. Will try some other ways.
